package me.kadarh.mecaworks.domain.alertes;

/**
 * @author kadarH
 */
public enum TypeAlerte {
	COMPTEUR_H_EN_PANNE,
	COMPTEUR_KM_EN_PANNE,
	COMPTEUR_H_REPARE,
	COMPTEUR_KM_REPARE,
	CHAUFFEUR_CHANGED,
	CONSOMMATION_H_ANNORMALE,
	CONSOMMATION_KM_ANNORMALE,
	QUANTITE_MORE_THAN_RESERVOIR,
}
